In [6]:
import pandas as pd 
import numpy as np

In [7]:
dados=pd.read_csv('ArmasApreendidasEvolucaoCisp.csv', sep=';')
display(dados.head())

,cisp,mes,ano,aisp,risp,arma_fogo_arma_fabricacao_caseira,arma_fogo_carabina,arma_fogo_espingarda,arma_fogo_fuzil,arma_fogo_garrucha,...,simulacro_fuzil,simulacro_garrucha,simulacro_garruchao,simulacro_metralhadora,simulacro_outros,simulacro_paintball,simulacro_pistola,simulacro_revolver,simulacro_submetralhadora,simulacro_total
0,1,1,2007,5,1,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,2,2007,5,1,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,3,2007,5,1,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,4,2007,5,1,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,5,2007,5,1,0,0,0,0,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
estatisca=dados.describe()
display(estatisca)

,cisp,mes,ano,aisp,risp,arma_fogo_arma_fabricacao_caseira,arma_fogo_carabina,arma_fogo_espingarda,arma_fogo_fuzil,arma_fogo_garrucha,...,simulacro_fuzil,simulacro_garrucha,simulacro_garruchao,simulacro_metralhadora,simulacro_outros,simulacro_paintball,simulacro_pistola,simulacro_revolver,simulacro_submetralhadora,simulacro_total
count,29736.000000,29736.000000,29736.000000,29736.000000,29736.000000,29736.000000,29736.000000,29736.000000,29736.000000,29736.000000,...,18144.000000,18144.000000,18144.000000,18144.000000,18144.000000,18144.000000,18144.000000,18144.000000,18144.000000,18144.000000
mean,81.581114,6.500000,2015.485472,20.701170,3.854722,0.089689,0.054580,0.443503,0.217380,0.087806,...,0.041060,0.001433,0.000276,0.001598,0.033014,0.001598,0.558091,0.022983,0.002480,0.730710
std,48.297678,3.452111,5.185393,11.415816,2.011673,0.730875,0.285424,1.093372,1.077661,0.363074,...,0.241987,0.051416,0.019640,0.041305,0.223369,0.039948,1.125160,0.153845,0.050837,1.357017
min,1.000000,1.000000,2007.000000,2.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,38.000000,3.750000,2011.000000,10.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,78.000000,6.500000,2015.000000,21.000000,4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,125.000000,9.250000,2020.000000,31.000000,6.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000
max,168.000000,12.000000,2024.000000,43.000000,7.000000,35.000000,12.000000,35.000000,62.000000,9.000000,...,7.000000,5.000000,2.000000,2.000000,12.000000,1.000000,12.000000,2.000000,2.000000,14.000000

In [ ]:
df_copia=dados.copy()
display(df_copia)

,cisp,mes,ano,aisp,risp,arma_fogo_arma_fabricacao_caseira,arma_fogo_carabina,arma_fogo_espingarda,arma_fogo_fuzil,arma_fogo_garrucha,...,simulacro_fuzil,simulacro_garrucha,simulacro_garruchao,simulacro_metralhadora,simulacro_outros,simulacro_paintball,simulacro_pistola,simulacro_revolver,simulacro_submetralhadora,simulacro_total
0,1,1,2007,5,1,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,2,2007,5,1,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,3,2007,5,1,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,4,2007,5,1,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,5,2007,5,1,0,0,0,0,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29731,168,8,2024,28,5,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29732,168,9,2024,28,5,0,0,1,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29733,168,10,2024,28,5,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29734,168,11,2024,28,5,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29735,168,12,2024,28,5,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0